
# Setup
title:               PACSTRAT
email:               skam@pacstrat.org
tagline:             A Global Mission Support Company
url:                 "http://www.pacstrat.org" # insert your site's URL
baseurl:             "http://www.pacstrat.org"

# About/contact
author: # you can edit these to be your personal details
  name:              Poidog.co
  url:               https://www.poidog.co
  email:             info@poidog.co

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Social
github_username: 
twitter_username: 
instagram_username: 
facebook: 
linkedin_username: 
dribbble_username: 

# Custom vars
version:             1.0.1
github:
  repo:              

# Gems - Dependencies for this theme
gems:
  # None currently

# Build settings
markdown:     kramdown
permalink:    pretty
